
addons:
 apt:
  packages:
   - ncurses-dev
   - docutils-common
   - bison
   - flex
   - libglade2-dev
   - lintian
   - golang
   - perl
   - python
   - nodejs

script:
 - make && sudo make deb && sudo dpkg -i nct.deb && make test
