#!/bin/bash

#
# Copyright (C) 2016 nCrux
# Author: Aditi <aditi@ncrux.com>
#

#
# Generates C Header file for a given configuration file
#

H_DEF=__`basename $2 | tr '.-' '_'| tr  '[:lower:]' '[:upper:]'`

awk -v H_DEF=$H_DEF '
BEGIN {
	group_comment = 0;
	FS = "=";
	printf "#ifndef " H_DEF "\n#define " H_DEF "\n";
	printf "\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";
}

END {
	printf "\n#ifdef __cplusplus\n}\n#endif\n\n";
	printf "#endif /* " H_DEF " */";
}

# Ignore blank lines
/^$/ { next; }

# Beginning/End of group comment
/^#$/ {
	if (group_comment == 0) {
		printf "\n/*\n";
		group_comment = 1;
	} else {
		printf " */\n";
		group_comment = 0;
	}
	next;
}

# Comments (Individual/Group comment)
/^#/ {
	gsub("^# ","");
	if (group_comment) {
		printf " * " $0 "\n";
	} else {
		printf "/* " $0 " */\n";
	}
	next;
}

# Split valid lines into two words: w1 and w2
{
	i = index($0, "=");
	w1 = substr($0, 1, i-1);
	w2 = substr($0, i+1);
}

/* C Header File */
{
	if (w2 == "y") {
		print "#define " w1 " 1";
	} else if(w2 == "m") {
		print "#define " w1 "_MODULE 1";
	} else {
		print "#define " w1 " " w2;
	}
	next;
}


' $1 > $2

exit 0
